### ISSUE TITLE
When /data is mounted db's are not persisting

### ISSUE THREAD

**Issue by yankees9920** [tutumcloud/influxdb#75]
I have my data folder mounted to my local machine however when I start the server the first time my users and my databases are created. 
Then when I stop and restart the server it seems to recognize that this has already been created and doesn't create it again, however, this data does not seem to have persisted and I am left without my databases and admin user.

Here is my compose file:
```
influxdb:
    image: tutum/influxdb
    hostname: influx
    name: influx
    environment:
        - ADMIN_USER=user
        - INFLUXDB_INIT_PWD=password
        - PRE_CREATE_DB=cadvisor
    ports:
        - "8083:8083"
        - "8086:8086"
    expose:
        - "8090"
        - "8099"
    volumes:
        - ./influxdb/data:/data
        - ./influxdb/config:/config
    restart: always
```
